services:
  glpi:
    image: aprendendolinux/glpi:latest
    container_name: glpi
    hostname: glpi
    environment:
      - TIMEZONE=${TIMEZONE}
      - VERSION=${VERSION}
      - UPLOAD_MAX_FILESIZE=${UPLOAD_MAX_FILESIZE}
      - POST_MAX_FILESIZE=${POST_MAX_FILESIZE}
    volumes:
      - glpi:/var/www/html
    ports:
      - "80:80"
    restart: always
    depends_on:
      - mariadb

  mariadb:
    image: mariadb:latest
    container_name: mariadb
    hostname: glpi
    environment:
      - MARIADB_ROOT_PASSWORD=${MARIADB_ROOT_PASSWORD}
      - MARIADB_DATABASE=${MARIADB_DATABASE}
      - MARIADB_USER=${MARIADB_USER}
      - MARIADB_PASSWORD=${MARIADB_PASSWORD}
    volumes:
      - /srv/mariadb:/var/lib/mysql
    restart: always

volumes:
  glpi:

